### ISSUE TITLE
Error when shutting down: AttributeError: module 'collections' has no attribute 'Iterable'

### ISSUE THREAD

**Issue by rubo77** [rubo77/Goldkarpfen#1]
```
  ## shutting down hidden service                                                                                 │  II no new version for sovieldazu-1NnBPac1khn1axmnvAmdaDNQHb8HsZK7b5.itp.tar.gz
Traceback (most recent call last):                                                                                │prt-01pJFCF3YGfyNgEDDNWHbBUMyeS2Rkgpux.itp.tar.gz
  File "/home/ruben/Goldkarpfen/stop-hidden-service.py", line 14, in <module>                                     │######################################################################## 100,0%
    controller.remove_hidden_service(hidden_service_dir)                                                          │itp-files/prt-01pJFCF3YGfyNgEDDNWHbBUMyeS2Rkgpux.itp
  File "/usr/lib/python3/dist-packages/stem/control.py", line 2888, in remove_hidden_service                      │  II no new version for Gartenkraut-1BKvMKnjirBGc33GoyZ5tCUUV6jfUN1ek5.itp.tar.gz
    self.set_hidden_service_conf(conf)                                                                            │elo-136DfzHespMkFVHgfBwG8EH6HgJcrDqVuN.itp.tar.gz
  File "/usr/lib/python3/dist-packages/stem/control.py", line 2705, in set_hidden_service_conf                    │######################################################################## 100,0%
    self.reset_conf('HiddenServiceDir')                                                                           │itp-files/elo-136DfzHespMkFVHgfBwG8EH6HgJcrDqVuN.itp
  File "/usr/lib/python3/dist-packages/stem/control.py", line 2488, in reset_conf                                 │  II no new version for PosRotTurm-1485ZHEwk4kDNhYzpi9TnNZsZYob8n5ijq.itp.tar.gz
    self.set_options(dict([(entry, None) for entry in params]), True)                                             │  II no new version for robin-18Z9RY3Ea3EkKSjNGVDTPGntczBfPMhpwN.itp.tar.gz
  File "/usr/lib/python3/dist-packages/stem/control.py", line 2535, in set_options                                │Goldkarpfen-latest.tar.gz
    elif isinstance(value, collections.Iterable):                                                                 │######################################################################## 100,0%
AttributeError: module 'collections' has no attribute 'Iterable'

**Comment by rubo77** [comment]
it is possible to manually fix it in 

    sudo vi /usr/lib/python3/dist-packages/stem/control.py

LINE 2535:

      elif isinstance(value, collections.Iterable):

change this to 

      elif isinstance(value, collections.abc.Iterable): # fixed by ruben

But it would be better to find out the p`pip` package that serves this file. I tried upgrading `stem` but that doesn't seem to be the package

**Comment by rubo77** [comment]
fixed in https://github.com/torproject/stem/commit/af71483f which is part of Stem release 1.8.1
